### PR TITLE
Check desired surface formats against feature flags

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
This comparison is a simple addition that proves helpful when the developer intends to use swapchain obtained images for cases like storage purposes.

### CODE REVIEW

**Comment by charles-lunarg** [comment]
This is a nice addition, and all the code looks idiomatic with the rest of the code base. 
At first I wondered why you only checked the `optimalTiling` but upon recollection and reading of the spec, I believe swapchain images must have a tiling mode of OPTIMAL_TILING (and they aren't buffers!) so there is no issue there.

Due to a cryptocurrency attack on Github Actions yesterday I disabled CI from running automatically, let me figure out how to get that happening and then we can see about merging this.

**Comment by mehmetoguzderin** [comment]
@charles-lunarg thanks a lot for the paying attention, that attack sounds quite bad, maybe I should do the same to my repos too. Indeed, spec specifies that to be the case, I don't know how to link the exact table but it is in this section (for the future reader): https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_wsi_swapchain

**Comment by charles-lunarg** [comment]
I was only inconvenienced by the attack (20 spam email messages and realizing there are scummy people online). It certainly hurt github much more than I.
So I pushed a commit to master that allowed manually starting of jobs, but only on branches in the repo. I think if you rebase on master to get that change, you could run it in your fork and i'll just check that.
Yes, thanks for linking the spec.

**Comment by mehmetoguzderin** [comment]
I think I am unable to (find the button to) run the job

**Comment by charles-lunarg** [comment]
Yeah, either you have to setup actions on your fork (which I don't know how or what that actually means) or I need to figure out more of the github-actions to fix whatever is preventing this from occurring.

**Comment by mehmetoguzderin** [comment]
Understood, PTAL here (in case it does the correct thing): https://github.com/mehmetoguzderin/vk-bootstrap/actions/runs/723878248

**Comment by charles-lunarg** [comment]
Ah sweet. I think I can merge this, logic checks out and it passes the CI (in your fork).
I'm not sure what to do about running CI in the future, but for now me thinks asking contributors to manually run it should be fine.

Thanks for the contribution!

**Comment by mehmetoguzderin** [comment]
Thanks for maintaining this great project!

**Pull request merged**
